// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Quick proof the Dart→Rust→alotno-core chain is linked and callable.
String engineInfo() => RustLib.instance.api.crateApiSimpleEngineInfo();

Future<String> tracePngToSvg({
  required List<int> pngBytes,
  required TraceOptions options,
}) => RustLib.instance.api.crateApiSimpleTracePngToSvg(
  pngBytes: pngBytes,
  options: options,
);

Future<Uint8List> convertPngToPdf({
  required List<int> pngBytes,
  required TraceOptions options,
}) => RustLib.instance.api.crateApiSimpleConvertPngToPdf(
  pngBytes: pngBytes,
  options: options,
);

Future<String> convertPngToEps({
  required List<int> pngBytes,
  required TraceOptions options,
}) => RustLib.instance.api.crateApiSimpleConvertPngToEps(
  pngBytes: pngBytes,
  options: options,
);

Future<String> convertPngToDxf({
  required List<int> pngBytes,
  required TraceOptions options,
}) => RustLib.instance.api.crateApiSimpleConvertPngToDxf(
  pngBytes: pngBytes,
  options: options,
);

Future<Uint8List> convertPngToWebp({
  required List<int> pngBytes,
  required double quality,
  required bool lossless,
  required bool mono,
}) => RustLib.instance.api.crateApiSimpleConvertPngToWebp(
  pngBytes: pngBytes,
  quality: quality,
  lossless: lossless,
  mono: mono,
);

/// Bridge-friendly mirror of the core SVG options (strings map via core `parse`).
class TraceOptions {
  final String preset;
  final String colorMode;
  final String curveType;
  final String stacking;
  final int posterizeSteps;
  final int threshold;
  final String version;
  final String drawStyle;
  final String groupBy;

  /// Empty string = keep each shape's traced color.
  final String strokeColor;
  final double strokeWidth;
  final bool nonScalingStroke;
  final bool fixedSize;
  final bool adobeCompat;
  final bool clipOverflow;

  const TraceOptions({
    required this.preset,
    required this.colorMode,
    required this.curveType,
    required this.stacking,
    required this.posterizeSteps,
    required this.threshold,
    required this.version,
    required this.drawStyle,
    required this.groupBy,
    required this.strokeColor,
    required this.strokeWidth,
    required this.nonScalingStroke,
    required this.fixedSize,
    required this.adobeCompat,
    required this.clipOverflow,
  });

  static Future<TraceOptions> default_() =>
      RustLib.instance.api.crateApiSimpleTraceOptionsDefault();

  @override
  int get hashCode =>
      preset.hashCode ^
      colorMode.hashCode ^
      curveType.hashCode ^
      stacking.hashCode ^
      posterizeSteps.hashCode ^
      threshold.hashCode ^
      version.hashCode ^
      drawStyle.hashCode ^
      groupBy.hashCode ^
      strokeColor.hashCode ^
      strokeWidth.hashCode ^
      nonScalingStroke.hashCode ^
      fixedSize.hashCode ^
      adobeCompat.hashCode ^
      clipOverflow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TraceOptions &&
          runtimeType == other.runtimeType &&
          preset == other.preset &&
          colorMode == other.colorMode &&
          curveType == other.curveType &&
          stacking == other.stacking &&
          posterizeSteps == other.posterizeSteps &&
          threshold == other.threshold &&
          version == other.version &&
          drawStyle == other.drawStyle &&
          groupBy == other.groupBy &&
          strokeColor == other.strokeColor &&
          strokeWidth == other.strokeWidth &&
          nonScalingStroke == other.nonScalingStroke &&
          fixedSize == other.fixedSize &&
          adobeCompat == other.adobeCompat &&
          clipOverflow == other.clipOverflow;
}
