// Conversion worker: loads the WASM core and runs every PNG→{svg,pdf,eps,dxf,webp}
// conversion off the main thread, so large or batch jobs never freeze the tab.
// The dispatch logic lives in convert.core.ts (pure + unit-tested); this file is
// just the WASM + postMessage wiring.
//
// Protocol (main ↔ worker):
//   ← { type: "ready", lossySupported }
//   → { type: "convert", reqId, files, formats, opts, lossless, mono }
//   ← { type: "progress", reqId, done, total }
//   ← { type: "result", reqId, out, inBytes, outBytes, failed }

// @ts-expect-error generated by wasm-pack (see astro.config.mjs @wasm alias)
import init, * as wasm from "@wasm/alotno_wasm.js";
import { convertBatch, type ConvertMsg, type WasmApi } from "./convert.core";

// `globalThis` is typed as a Window under the DOM lib; cast to the worker
// surface we use.
type WorkerCtx = {
  postMessage: (message: unknown) => void;
  onmessage: ((e: MessageEvent) => void) | null;
};
const ctx = globalThis as unknown as WorkerCtx;

// Top-level await: a module worker queues incoming messages until the module
// (including this await) finishes evaluating, so no ready-gating is needed.
await init();
ctx.postMessage({ type: "ready", lossySupported: wasm.webpLossySupported() });

ctx.onmessage = (e: MessageEvent) => {
  const msg = e.data as ConvertMsg;
  if (msg?.type !== "convert") return;
  convertBatch(msg, wasm as unknown as WasmApi, (m) => ctx.postMessage(m));
};
