// Conversion worker: loads the WASM core and runs every PNG→{svg,pdf,eps,dxf,webp}
// conversion off the main thread, so large or batch jobs never freeze the tab.
//
// Protocol (main ↔ worker):
//   ← { type: "ready", lossySupported }
//   → { type: "convert", reqId, files, formats, opts, lossless, mono }
//   ← { type: "progress", reqId, done, total }
//   ← { type: "result", reqId, out, inBytes, outBytes, failed }

// @ts-expect-error generated by wasm-pack (see astro.config.mjs @wasm alias)
import init, * as wasm from "@wasm/alotno_wasm.js";

type Opts = { preset: string; colorMode: string; curveType: string };
type ConvertMsg = {
  type: "convert";
  reqId: number;
  files: { name: string; bytes: Uint8Array }[];
  formats: string[];
  opts: Opts;
  lossless: boolean;
  mono: boolean;
};

// `self` is typed as a Window under the DOM lib; cast to the worker surface we use.
type WorkerCtx = {
  postMessage: (message: unknown) => void;
  onmessage: ((e: MessageEvent) => void) | null;
};
const ctx = self as unknown as WorkerCtx;

const enc = new TextEncoder();

const ready = (async () => {
  await init();
  ctx.postMessage({ type: "ready", lossySupported: wasm.webpLossySupported() });
})();

ctx.onmessage = async (e: MessageEvent) => {
  const msg = e.data as ConvertMsg;
  if (msg?.type !== "convert") return;
  await ready;

  const out: Record<string, Uint8Array> = {};
  const failed: { name: string; fmt: string; error: string }[] = [];
  let inBytes = 0;
  let outBytes = 0;
  let done = 0;

  for (const f of msg.files) {
    inBytes += f.bytes.length;
    const base = f.name.replace(/\.png$/i, "");
    for (const fmt of msg.formats) {
      // Per-file/format try/catch: one bad PNG can't abort the whole batch.
      try {
        let data: Uint8Array;
        if (fmt === "svg") data = enc.encode(wasm.pngToSvg(f.bytes, msg.opts));
        else if (fmt === "eps") data = enc.encode(wasm.pngToEps(f.bytes, msg.opts));
        else if (fmt === "dxf") data = enc.encode(wasm.pngToDxf(f.bytes, msg.opts));
        else if (fmt === "pdf") data = wasm.pngToPdf(f.bytes, msg.opts);
        else data = wasm.pngToWebp(f.bytes, 82, msg.lossless, msg.mono);
        out[`${base}.${fmt}`] = data;
        outBytes += data.length;
      } catch (err) {
        failed.push({ name: f.name, fmt, error: String(err) });
      }
    }
    done++;
    ctx.postMessage({ type: "progress", reqId: msg.reqId, done, total: msg.files.length });
  }

  ctx.postMessage({ type: "result", reqId: msg.reqId, out, inBytes, outBytes, failed });
};
