// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 2084377502;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_alotno',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiSimpleConvertPngToDxf({
    required List<int> pngBytes,
    required TraceOptions options,
  });

  Future<String> crateApiSimpleConvertPngToEps({
    required List<int> pngBytes,
    required TraceOptions options,
  });

  Future<Uint8List> crateApiSimpleConvertPngToPdf({
    required List<int> pngBytes,
    required TraceOptions options,
  });

  Future<Uint8List> crateApiSimpleConvertPngToWebp({
    required List<int> pngBytes,
    required double quality,
    required bool lossless,
    required bool mono,
  });

  String crateApiSimpleEngineInfo();

  Future<void> crateApiSimpleInitApp();

  Future<TraceOptions> crateApiSimpleTraceOptionsDefault();

  Future<String> crateApiSimpleTracePngToSvg({
    required List<int> pngBytes,
    required TraceOptions options,
  });

  bool crateApiSimpleWebpLossySupportedNative();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiSimpleConvertPngToDxf({
    required List<int> pngBytes,
    required TraceOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pngBytes, serializer);
          sse_encode_box_autoadd_trace_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleConvertPngToDxfConstMeta,
        argValues: [pngBytes, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleConvertPngToDxfConstMeta =>
      const TaskConstMeta(
        debugName: "convert_png_to_dxf",
        argNames: ["pngBytes", "options"],
      );

  @override
  Future<String> crateApiSimpleConvertPngToEps({
    required List<int> pngBytes,
    required TraceOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pngBytes, serializer);
          sse_encode_box_autoadd_trace_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleConvertPngToEpsConstMeta,
        argValues: [pngBytes, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleConvertPngToEpsConstMeta =>
      const TaskConstMeta(
        debugName: "convert_png_to_eps",
        argNames: ["pngBytes", "options"],
      );

  @override
  Future<Uint8List> crateApiSimpleConvertPngToPdf({
    required List<int> pngBytes,
    required TraceOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pngBytes, serializer);
          sse_encode_box_autoadd_trace_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleConvertPngToPdfConstMeta,
        argValues: [pngBytes, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleConvertPngToPdfConstMeta =>
      const TaskConstMeta(
        debugName: "convert_png_to_pdf",
        argNames: ["pngBytes", "options"],
      );

  @override
  Future<Uint8List> crateApiSimpleConvertPngToWebp({
    required List<int> pngBytes,
    required double quality,
    required bool lossless,
    required bool mono,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pngBytes, serializer);
          sse_encode_f_32(quality, serializer);
          sse_encode_bool(lossless, serializer);
          sse_encode_bool(mono, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleConvertPngToWebpConstMeta,
        argValues: [pngBytes, quality, lossless, mono],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleConvertPngToWebpConstMeta =>
      const TaskConstMeta(
        debugName: "convert_png_to_webp",
        argNames: ["pngBytes", "quality", "lossless", "mono"],
      );

  @override
  String crateApiSimpleEngineInfo() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleEngineInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEngineInfoConstMeta =>
      const TaskConstMeta(debugName: "engine_info", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<TraceOptions> crateApiSimpleTraceOptionsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_trace_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTraceOptionsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTraceOptionsDefaultConstMeta =>
      const TaskConstMeta(debugName: "trace_options_default", argNames: []);

  @override
  Future<String> crateApiSimpleTracePngToSvg({
    required List<int> pngBytes,
    required TraceOptions options,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pngBytes, serializer);
          sse_encode_box_autoadd_trace_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTracePngToSvgConstMeta,
        argValues: [pngBytes, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTracePngToSvgConstMeta =>
      const TaskConstMeta(
        debugName: "trace_png_to_svg",
        argNames: ["pngBytes", "options"],
      );

  @override
  bool crateApiSimpleWebpLossySupportedNative() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleWebpLossySupportedNativeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleWebpLossySupportedNativeConstMeta =>
      const TaskConstMeta(
        debugName: "webp_lossy_supported_native",
        argNames: [],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  TraceOptions dco_decode_box_autoadd_trace_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_trace_options(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  TraceOptions dco_decode_trace_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return TraceOptions(
      preset: dco_decode_String(arr[0]),
      colorMode: dco_decode_String(arr[1]),
      curveType: dco_decode_String(arr[2]),
      stacking: dco_decode_String(arr[3]),
      posterizeSteps: dco_decode_u_8(arr[4]),
      threshold: dco_decode_u_8(arr[5]),
      version: dco_decode_String(arr[6]),
      drawStyle: dco_decode_String(arr[7]),
      groupBy: dco_decode_String(arr[8]),
      strokeColor: dco_decode_String(arr[9]),
      strokeWidth: dco_decode_f_32(arr[10]),
      nonScalingStroke: dco_decode_bool(arr[11]),
      fixedSize: dco_decode_bool(arr[12]),
      adobeCompat: dco_decode_bool(arr[13]),
      clipOverflow: dco_decode_bool(arr[14]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  TraceOptions sse_decode_box_autoadd_trace_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_trace_options(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  TraceOptions sse_decode_trace_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_preset = sse_decode_String(deserializer);
    var var_colorMode = sse_decode_String(deserializer);
    var var_curveType = sse_decode_String(deserializer);
    var var_stacking = sse_decode_String(deserializer);
    var var_posterizeSteps = sse_decode_u_8(deserializer);
    var var_threshold = sse_decode_u_8(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_drawStyle = sse_decode_String(deserializer);
    var var_groupBy = sse_decode_String(deserializer);
    var var_strokeColor = sse_decode_String(deserializer);
    var var_strokeWidth = sse_decode_f_32(deserializer);
    var var_nonScalingStroke = sse_decode_bool(deserializer);
    var var_fixedSize = sse_decode_bool(deserializer);
    var var_adobeCompat = sse_decode_bool(deserializer);
    var var_clipOverflow = sse_decode_bool(deserializer);
    return TraceOptions(
      preset: var_preset,
      colorMode: var_colorMode,
      curveType: var_curveType,
      stacking: var_stacking,
      posterizeSteps: var_posterizeSteps,
      threshold: var_threshold,
      version: var_version,
      drawStyle: var_drawStyle,
      groupBy: var_groupBy,
      strokeColor: var_strokeColor,
      strokeWidth: var_strokeWidth,
      nonScalingStroke: var_nonScalingStroke,
      fixedSize: var_fixedSize,
      adobeCompat: var_adobeCompat,
      clipOverflow: var_clipOverflow,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_trace_options(
    TraceOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_trace_options(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_trace_options(TraceOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.preset, serializer);
    sse_encode_String(self.colorMode, serializer);
    sse_encode_String(self.curveType, serializer);
    sse_encode_String(self.stacking, serializer);
    sse_encode_u_8(self.posterizeSteps, serializer);
    sse_encode_u_8(self.threshold, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.drawStyle, serializer);
    sse_encode_String(self.groupBy, serializer);
    sse_encode_String(self.strokeColor, serializer);
    sse_encode_f_32(self.strokeWidth, serializer);
    sse_encode_bool(self.nonScalingStroke, serializer);
    sse_encode_bool(self.fixedSize, serializer);
    sse_encode_bool(self.adobeCompat, serializer);
    sse_encode_bool(self.clipOverflow, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
